### ISSUE TITLE
Some little improvement ideas

### ISSUE THREAD

**Issue by thobaut** [sosauce/CuteMusic#41]
Hey, it's me again
I really want to see this little app grow so here's a list of little quality of life changes that I think would be very cool to be implemented :

- Internal miniplayer same color as the background
-> Changing the color so it doesn't blend + idea for extension like an app general color theme for non-dark elements (like Symphony)

- Remembering if you previously activated random next song mode
-> Right now, upon leaving the app, the default mode will reset to next song in the library (so in alphabetical order)
-> Can also be extended to speed and pitch, they are going back to default too

- Import/Export of settings
-> No idea how hard it would be to be implemented, but I think it would be great to be able to import our settings to another device

**Comment by sosauce** [comment]
1. There is WIP to add color scheme based on the art of the current music's art and some UI customizations in general!
2. Used to exist but due to bad code I removed them, but now that the code is better I can deffo bring back !
3. Do you mean on the Now Playing screen ?
4. Part of upcoming customizations!
5. Theres so little settings right now that's it's not yet worth to do 
6. Yeah I wish I could figure out translation platforms :(

**Comment by thobaut** [comment]
1. Oh not bad, but I meant like choosing a specific color for non-dark elements
3. I guess it is yes, I meant the screen where you can control the current music playing

I'm happy that most of the feature are getting added
Even tho I'm pretty good in Java and not in Kotlin, I might try to download Android Studio and contribute at my humble level (and free time between my studies) and add try to add some little things here and there
